apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: albergue-oporto
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 31111
  selector:
    app: albergue-oporto
